replicaCount: 1

image:
  repository: x-word
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  grpc:
    port: grpc
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  grpc:
    port: grpc
  initialDelaySeconds: 3
  periodSeconds: 5

env:
  GRPC_PORT: "8080"
